### PR TITLE
62 exceptions

### LINKED ISSUE #62: Exceptions
Create appropriate exception handlers

### PR DESCRIPTION
**Pull request by idafum**

### CODE REVIEW

File: CombatCrittersSharp/exception/GeneralExceptionHandler.cs [hunk 1]
```diff
@@ -0,0 +1,77 @@
...
+
+            // Log the exception with details
+            LogException(ex, customMessage);
+
+            // Re-throw a new CombatCrittersException with detailed information
+            throw new CombatCrittersException(
+                customMessage ?? "An error occurred in CombatCrittersSharp wrapper.",
+                detailedMessage,
+                ex
+            );
```
Comment (VanJackal) [inline CombatCrittersSharp/exception/GeneralExceptionHandler.cs]: wrapping every exception like this will prevent the catching of more specific errors in the ui

File: CombatCrittersSharp/managers/PacksManager.cs [hunk 2]
```diff
@@ -113,21 +127,40 @@ public async Task<List<UserPack>> GetUserPacksAsync(int userId)
             }
             catch (RestException e) when (e.StatusCode == HttpStatusCode.Forbidden)
             {
-                throw new AuthException("Access denied, Failed to get decks", e);
+                // Log the forbidden access and return null
+                GeneralExceptionHandler.HandleException(e, "Access denied. Failed to retrieve pack by ID in PacksManager.");
+                return new List<UserPack>();
```
Comment (VanJackal) [inline CombatCrittersSharp/managers/PacksManager.cs]: unreachable code, this applies to any time that something iis called after HandleException is called

File: CombatCrittersSharp/exception/GeneralExceptionHandler.cs [hunk 3]
```diff
@@ -0,0 +1,77 @@
...
+                case TimeoutException:
+                    details.AppendLine("Operation timed out.");
+                    break;
+                case ArgumentException argEx:
+                    details.AppendLine($"Invalid argument: {argEx.Message}");
+                    break;
+                default:
+                    details.AppendLine("Unexpected error.");
+                    break;
+            }
```
Comment (VanJackal) [inline CombatCrittersSharp/exception/GeneralExceptionHandler.cs]: instead of this the additional details could be added to the constructors of the exceptions. for the excetions that aren't custom they probably shouldnt be wrapped, or should be wrapped with new custom exceptions at their throw point

File: CombatCrittersSharp/managers/PacksManager.cs [hunk 4]
```diff
@@ -139,26 +172,37 @@ public async Task<Pack> CreatePackAsync(List<int> cardIds, Dictionary<int, int>
...
                     pack_details: new PackPayload(name: packName, image: packImage, packid: -1)
                 );
 
                 return await CreatePackOnServerAsync(payload);
             }
+            catch (ArgumentException ex)
+            {
+                GeneralExceptionHandler.HandleException(ex, "Invalid argument provided while creating pack in PacksManager.");
+                return null;
+            }
```
Comment (VanJackal) [inline CombatCrittersSharp/managers/PacksManager.cs]: don't catch exceptions thrown in the try block

File: CombatCrittersSharp/rest/Rest.cs [hunk 5]
```diff
@@ -54,11 +54,13 @@ private static StringContent ObjectToContent(object obj)
...
-    private static void CheckResponse(HttpResponseMessage response)
+    private static async Task CheckResponse(HttpResponseMessage response)
     {
         if (!response.IsSuccessStatusCode)
         {
-            throw new RestException("Request failed with status code " + response.StatusCode, response.StatusCode, response);
+            var content = await response.Content.ReadAsStringAsync();
+            throw new RestException($"Request failed with status code {response.StatusCode} and content: {content}",
+                                response.StatusCode, response);
         };
```
Comment (VanJackal) [inline CombatCrittersSharp/rest/Rest.cs]: It may be worth adding a catch for some of the regular exceptions here and throwing a WrapperNetworkException, as well as changing adding a throw for auth exception for whenever the status code is 403 or 401

**Review by VanJackal — CHANGES_REQUESTED** [review]
in general, errors shouldn't be handled in wrapper unless we are adding additional context. The GeneralExceptionHandler is removing the context from the exceptions that are thrown.

The better way (which I think you already started) is to have a single parent exception (CombatCrittersException) that is extended by any of the exceptions being thrown in the wrapper.

for stuff like ArgumentException, it shouldn't be wrapped, and probably shouldn't be caught in the ui either. If that is being thrown it implies the caller sent an invalid input, which it shouldn't do.

**Comment by idafum** [comment]
I'm kinda just getting the gist regarding exceptions. I'll fix these

**Review by VanJackal — APPROVED** [review]
