### PR TITLE
40 fix cards objects

### LINKED ISSUE #40: Fix cards objects

### PR DESCRIPTION
**Pull request by idafum**

### CODE REVIEW

File: CombatCrittersSharp/objects/card/CardQuery.cs [hunk 1]
```diff
@@ -1,18 +1,68 @@
...
+        private static string MapOrderToString(CardOrder order)
+        {
+            return order switch
+            {
+                CardOrder.NONE => "",
+                CardOrder.ID => "ID",
+                CardOrder.NAME => "NAME",
+                CardOrder.PLAYCOST => "PLAY_COST",
+                CardOrder.RARITY => "RARITY",
+                _ => throw new ArgumentOutOfRangeException(nameof(order), order, null)
```
Comment (VanJackal) [inline CombatCrittersSharp/objects/card/CardQuery.cs]: is there no way to define the enum with the strings?

File: CombatCrittersSharp/objects/card/CardQueryBuilder.cs [hunk 2]
```diff
@@ -1,36 +1,82 @@
...
+                _rarities,
+                _raritiesInclude
+            );
         }
 
-        public string GetQueryString()
+        public void Reset()
+        {
+            _cost = 0;
+            _costLess = true;
```
Comment (VanJackal) [inline CombatCrittersSharp/objects/card/CardQueryBuilder.cs]: cost less should default false otherwise by default you will get nothing from the query

File: CombatCrittersSharp/objects/card/Interfaces/ICardQuery.cs [hunk 3]
```diff
@@ -1,8 +1,21 @@
...
+
+        public enum CardOrder
+        {
+            NONE, // will map to ""
+            ID, // will map to "ID"
+            NAME, // will map to "NAME"
+            PLAYCOST, // will map to "PLAY_COST
+            RARITY // will map to "RARITY"
+        }
+
```
Comment (VanJackal) [inline CombatCrittersSharp/objects/card/Interfaces/ICardQuery.cs]: should probably be in a separate file

File: CombatCrittersSharp/rest/payloads/CardPayload.cs [hunk 4]
```diff
@@ -15,7 +15,8 @@ public record CardPayload(
     {
         public const string TypeCritter = "critter";
         public const string TypeItem = "item";
-        
+        internal int abilityId;
```
Comment (VanJackal) [inline CombatCrittersSharp/rest/payloads/CardPayload.cs]: this should be in the type_specific object

File: CombatCrittersSharp/objects/card/CardQueryBuilder.cs [hunk 5]
```diff
@@ -1,36 +1,82 @@
...
+
+        public void SetOwned(bool owned)
+        {
+            _owned = owned;
+        }
+
+        public void SetRarities(List<int> rarities)
+        {
+            _rarities = rarities;
+        }
```
Comment (VanJackal) [inline CombatCrittersSharp/objects/card/CardQueryBuilder.cs]: rarities should use the enum defined for the rarities

**Review by VanJackal — CHANGES_REQUESTED** [review]

File: CombatCrittersSharp/objects/card/CardQuery.cs (hunk 1 above)
Comment (idafum) [reply CombatCrittersSharp/objects/card/CardQuery.cs]: No, only if I use the enum ToString method. However, mapping works as well

File: CombatCrittersSharp/objects/card/CardQueryBuilder.cs (hunk 2 above)
Comment (idafum) [reply CombatCrittersSharp/objects/card/CardQueryBuilder.cs]: Okay

File: CombatCrittersSharp/objects/card/Interfaces/ICardQuery.cs (hunk 3 above)
Comment (idafum) [reply CombatCrittersSharp/objects/card/Interfaces/ICardQuery.cs]: Okay, yeah that makes more sense

File: CombatCrittersSharp/rest/payloads/CardPayload.cs (hunk 4 above)
Comment (idafum) [reply CombatCrittersSharp/rest/payloads/CardPayload.cs]: yes, thats true

File: CombatCrittersSharp/objects/card/CardQueryBuilder.cs (hunk 5 above)
Comment (idafum) [reply CombatCrittersSharp/objects/card/CardQueryBuilder.cs]: Okay, i though we were using just integers for now. Got it

File: CombatCrittersSharp/objects/card/CardQuery.cs [hunk 6]
```diff
@@ -4,15 +4,50 @@ namespace CombatCrittersSharp.objects.card
...
+            var orderString = _order == CardOrder.NONE? "" : _order.ToString(); 
+            if (!string.IsNullOrEmpty(orderString)) queryStrings.Add($"order={orderString}");
+
+
+            if (_owned) queryStrings.Add($"owned={_owned}");
+
+
+            if (_rarities.Count != 0)
+            {
+                var raritiesString = string.Join(",", _rarities.Select(r => r.ToString())); //Convert each rarity enum value to its string
```
Comment (VanJackal) [inline CombatCrittersSharp/objects/card/CardQuery.cs]: the actual query still needs to be integers

**Review by VanJackal — APPROVED** [review]
